### ISSUE TITLE
I'm tired of you doing things so much *better* than me.

### ISSUE THREAD

**Issue by PullJosh** [livewires/you-win#1]
[Stop it.](https://github.com/PullJosh/paw) :stuck_out_tongue_winking_eye:

**Comment by tjvr** [comment]
Sorry! Oh, and I wasn't aware this is something I've done before? :P

**Comment by PullJosh** [comment]
No, it's something *I've* done before.

... /s

**Comment by tjvr** [comment]
I meant (as I think you know): isn't this the first time I've copied you? :P

Anyway, I liberally borrow code from Nathan; that's the secret. ;-)

**Comment by PullJosh** [comment]
> liberally borrow

This is my new favorite synonym for "steal". :P
