### ISSUE TITLE
Consider avoiding object-style initializers

### ISSUE THREAD

**Issue by tjvr** [livewires/you-win#10]
While convenient for an expert, the current initialiser style:

```js
new Sprite({
  costume: '⛄',
  angle: 10,
  // ...
})
```

...is way harder for a beginner than the following would be:

```js
var snowman = new Sprite
snowman.costume =  '⛄'
snowman.angle = 10
// ...
```

The levels of nesting/brackets etc are a massive pain to manage for someone new to programming or new to JavaScript.

And as a bonus, this way we don't have to teach them separate syntaxes for initialisation and for changing things later.

@PullJosh @jamesdoc @isnit0 Thoughts?

I'm also considering replacing `forever(() => {…})` with `sprite.forever(() => {…})`.

**Comment by PullJosh** [comment]
This is definitely a good idea. :+1:

**Comment by tjvr** [comment]
Thanks for the feedback! I'm-a do this.

**Comment by tjvr** [comment]
What are our thoughts on this? :-)

> I'm also considering replacing forever(() => {…}) with sprite.forever(() => {…})

**Comment by PullJosh** [comment]
I suppose i'm not opposed to it, but I'm not sure I see a clear benefit either.

**Comment by tjvr** [comment]
Nesting/indentation is hard to get right.
If it begins with the same sprite name, it makes clear that it should go at the same level of indentation as the rest of the sprite attribute assignments.
It also makes the lifecycle clearer, since when the sprite is destroyed the forever will stop; less frequent need for the (imho confusing) `return false` to stop the forever loop.
