### ISSUE TITLE
Rect documentation?

### ISSUE THREAD

**Issue by heyitsmeuralex** [livewires/you-win#19]
It doesn't look like [https://github.com/livewires/you-win/blob/master/sheets/Reference.md](Reference.md) has anything on Rects - it doesn't even acknowledge their existence!

**Comment by tjvr** [comment]
No, it doesn't. And I think they (or Polygons?) might be slightly broken currently 🙃

**Comment by tjvr** [comment]
* Should also add 'em to the template & recommended `import` line.
