### ISSUE TITLE
Event handling

### ISSUE THREAD

**Issue by tjvr** [livewires/you-win#2]
In the current model, we have `tap` and `drag` events.

1. If the mouse/finger is tapped, and does not move, we dispatch a `tap` event.
2. If the mouse/finger is held, and begins to move, we send `drag` events until the pointer is released.

These are dispatched as follows:

- For each sprite, topmost first, we dispatch the event. If it returns `false`, the sprite now "owns" the event.
- After `return false`, no further events are dispatched.
- `drag` events, for each drag, are sent to the sprite that handled the first drag event by returning `false`.
- If a sprite does *not* return `false` for the initial `drag` event, then it will receive no further events for that drag.
- The world receives drag events only if no sprite responded to the initial event.

In this way, each drag event is "owned" by a single sprite, or the world, depending on who captured the initial event. I'm not sure I'm happy with this. Thoughts, anyone? :)

**Comment by tjvr** [comment]
@PullJosh Do you have opinions on this too? :-)

**Comment by tjvr** [comment]
Additional API design consideration: how to detect a `drop` event.

**Comment by PullJosh** [comment]
This makes sense. Being able to drag one sprite at a time is a common feature that will be much easier with this method.

I can't imagine a lot of cases where drag events would need to sent to every sprite.

**Comment by tjvr** [comment]
@PullJosh any ideas how to signal the end of a drag? Should there be a separate `drop` event, or do we just signal the end by a flag on the event (`e.isFinished`)? Should the drop event have its own bubbling, so the thing you drag the Sprite into also gets the event? Argh.

**Comment by PullJosh** [comment]
I have to imagine that the best way to find out is to start using you `you-win` for real projects, and then determine which would be easiest to use.

**Comment by heyitsmeuralex** [comment]
+1 to `drop` events!

Perhaps there could be an api for recieving events even if other sprites eat the event? Something like `on.every('tap', ...)` (I have no idea what the current api is for events, though) would dispatch whenever anything is tapped, even if a dispatch returns false.

**Comment by tjvr** [comment]
Added `drop` events in 7819b81. Hopefully they even work!
