### ISSUE TITLE
Rename x/y

### ISSUE THREAD

**Issue by tjvr** [livewires/you-win#21]
Consider `xPos` or `centerX`.

**Comment by heyitsmeuralex** [comment]
Could you use get/setters?

```js
box.position.x = 25 // top left
console.log(box.position.centerX) // changes dynamically based on position.x
```

**Comment by tjvr** [comment]
I'm already using getters and setters everywhere :-)

`x` is currently defined as the center; you can also use `left` and `right` to set the edge positions.

I'm thinking about renaming `x`, though.

**Comment by tjvr** [comment]
Going with `posX` and `posY`.

**Comment by tjvr** [comment]
600f664.
