### ISSUE TITLE
'posX' doesn't do anything

### ISSUE THREAD

**Issue by nanaian** [livewires/you-win#29]
~~Looks like [this line](https://github.com/livewires/you-win/blob/master/uw/index.js#L916) uses `.x` rather than `.posX`. Whoops!~~

**Comment by tjvr** [comment]
> [this line](https://github.com/livewires/you-win/blob/master/uw/index.js#L916) uses `.x`

No, that's correct; that line relates to text rendering.

Can you clarify what bug you're reporting? :)

**Comment by heyitsmeuralex** [comment]
<sup>oh</sup>

`sprite.posX` doesn't seem to do anything when I remix the Glitch you-win template... `.x` works fine, however.

**Comment by tjvr** [comment]
I think that means the Glitch template needs updating!
